"""Utility functions for linear algebra assignments."""

from .determinants import (
    det_2x2,
    det_3x3_sarrus,
    det_cofactor,
    det_gauss,
    eh_invertivel,
    inversa_2x2,
    inversa_gauss_jordan,
)
from .geometry import (
    intersecao_reta_plano,
    plano_cartesiano_para_parametrico,
    plano_parametrico,
    posicao_relativa_planos,
    posicao_relativa_retas_2d,
    posicao_relativa_retas_3d,
    reta_2d,
    reta_3d,
    superficie_cilindro,
    superficie_cone,
    superficie_esfera,
    superficie_revolucao,
)
from .geometry2d import LinearMap2D, apply_linear_map, unit_circle, unit_square
from .lu import (
    decomposicao_lu,
    det_via_lu,
    resolver_lu,
    resolver_lu_multiplos_rhs,
)
from .matrices import (
    classificar_matriz,
    criar_diagonal,
    criar_identidade,
    criar_matriz_nula,
    criar_simetrica,
    criar_triangular_inferior,
    criar_triangular_superior,
    dimensao,
    eh_quadrada,
)
from .checks import RelativeError, assert_close, is_orthonormal, is_upper_triangular, relative_error
from .decompositions import qr_gram_schmidt
from .eigen import Eigen2x2Result, PowerIterationResult, eigen_2x2, power_iteration, rayleigh_quotient
from .least_squares import LeastSquaresResult, least_squares_normal_eq, least_squares_qr
from .systems import (
    classificar_sistema,
    cramer,
    cramer_2x2,
    cramer_3x3,
    escalonar,
    resolver_gauss,
    solve,
    substituicao_retroativa,
)
from .vectors import angle, dot, norm, projection

__all__ = [
    "classificar_matriz",
    "criar_diagonal",
    "criar_identidade",
    "criar_matriz_nula",
    "criar_simetrica",
    "criar_triangular_inferior",
    "criar_triangular_superior",
    "dimensao",
    "eh_quadrada",
    "det_2x2",
    "det_3x3_sarrus",
    "det_cofactor",
    "det_gauss",
    "eh_invertivel",
    "inversa_2x2",
    "inversa_gauss_jordan",
    "classificar_sistema",
    "cramer",
    "cramer_2x2",
    "cramer_3x3",
    "escalonar",
    "resolver_gauss",
    "substituicao_retroativa",
    "decomposicao_lu",
    "det_via_lu",
    "resolver_lu",
    "resolver_lu_multiplos_rhs",
    "intersecao_reta_plano",
    "plano_cartesiano_para_parametrico",
    "plano_parametrico",
    "posicao_relativa_planos",
    "posicao_relativa_retas_2d",
    "posicao_relativa_retas_3d",
    "reta_2d",
    "reta_3d",
    "superficie_cilindro",
    "superficie_cone",
    "superficie_esfera",
    "superficie_revolucao",
    "LinearMap2D",
    "apply_linear_map",
    "unit_circle",
    "unit_square",
    "RelativeError",
    "relative_error",
    "assert_close",
    "is_orthonormal",
    "is_upper_triangular",
    "qr_gram_schmidt",
    "Eigen2x2Result",
    "PowerIterationResult",
    "eigen_2x2",
    "power_iteration",
    "rayleigh_quotient",
    "LeastSquaresResult",
    "least_squares_normal_eq",
    "least_squares_qr",
    "solve",
    "angle",
    "dot",
    "norm",
    "projection",
]
