blank_issues_enabled: true
contact_links:
  - name: Submission Guide
    url: https://github.com/diogoribeiro7/linear-algebra-with-python/blob/main/assignments/submissions/4025XXX/SUBMISSION_GUIDE.md
    about: Read the submission process and requirements
