name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-python:
    runs-on: ubuntu-latest
    env:
      PYTHONNOUSERSITE: "1"
    strategy:
      matrix:
        python-version: ["3.11","3.12","3.13"]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1
      - run: poetry install
        working-directory: packages/python
      - run: poetry run ruff check src/ tests/
        working-directory: packages/python
      - run: poetry run mypy src/ --ignore-missing-imports
        working-directory: packages/python
      - run: poetry run pytest --tb=short
        working-directory: packages/python

  test-js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20", "22"]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - run: yarn install --immutable
        working-directory: packages/js
      - run: yarn test
        working-directory: packages/js
