name: Docs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1
      - run: poetry install
        working-directory: packages/python
      - run: poetry run mkdocs build -f ../../mkdocs.yml
        working-directory: packages/python
